# file: group_vars/osx.yml

---
# executables -------------------------------------------------------------
executables:
  brew: /usr/local/bin/brew
  vim: /usr/bin/vim
  zsh: /usr/bin/zsh

# auth --------------------------------------------------------------------
lasko:
  user:
    name: lasko 
    group: staff
    shell: "{{ executables.zsh }}"
  home: /home/lasko
