---
 # Ensure our vim directory exists
- name: ensure target directory exists
  file:
    dest={{ vim.home }}
    state=directory
  tags: vim

- name: "Install Pathogen for user" 
  file: path={{ item }} group=lasko owner=lasko state=directory
  with_items:
  - "{{ lasko.home }}/.vim/autoload"
  - "{{ lasko.home }}/.vim/bundle"
  - "{{ lasko.home }}/.vim/colors"
  - "{{ lasko.home }}/.vim/fonts"
  tags: vim

- name: Install pathogen for user 'lasko' - download code
  get_url: url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest={{ lasko.home }}/.vim/autoload validate_certs=no
  tags: vim

- name: Add CtrlP Repo
  git: repo={{ ctrlp.repo }} dest={{ ctrlp.dest }}
  tags: vim

- name: Add Nerdtree Repo
  git: repo={{ nerdtree.repo }} dest={{ nerdtree.dest }}
  tags: vim

- name: Add Syntastic Repo
  git: repo={{ syntastic.repo }} dest={{ syntastic.dest }}
  tags: vim

- name: Add Vim-Airline Repo
  git: repo={{ vimairline.repo }} dest={{ vimairline.dest }}
  tags: vim

- name: Add Vim-Colors-Solarized Repo
  get_url: url=https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim dest={{ lasko.home }}/.vim/colors validate_certs=no
  tags: vim

- name: Add Powerline Fonts
  git: repo={{ powerlinefonts.repo }} dest={{ powerlinefonts.dest }}
  tags: vim

- name: execute font install
  script: {{ lasko.home }}/.vim/fonts/install.sh
  tags: vim

- name: copy vimrc file
  copy:
    src=vimrc
    dest={{lasko.home}}/.vimrc
  tags: vim

